version: '3.5'
services:
  vault:
    image: vault:latest
    container_name: vault
    ports:
      - "8200:8200/tcp"
    labels:
      com.konghq.gojira: "True"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: myroot
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    networks:
    - gojira